<a href="https://colab.research.google.com/github/Rahul-Chouhan-407/Practice_and_Assignments/blob/main/Intellipaat%20Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [134]:
name,age = "Suresh", 29 
print(name,age,"is a \"natural\" swimmer")

Suresh 29 is a "natural" swimmer


In [125]:
a,b,c = 10,20,50 
result = (a + b)//c 
print("The result is {}".format(c))

The result is 50


In [126]:
a = 10 
b = 20 
c = a**2 
d = b**2 
result = d - c 
result -= 100 
print(result)

200


In [127]:
a = 10 
b = 20 
print(a>b)

False


In [128]:
a = 10 
b = 10.0 
print(a is not b)

True


In [129]:
a = [10] 
b = {10,20} 
print(a[0] in b)

True


In [130]:
a = 10 
b = 20 
print(a > 5 & b > 15)

False


In [131]:
a = 10 
b = 20 
print(a > 5 or b > 15)

True


In [132]:
a = [1,2,3,4,5]
b = [2,3,4,5,6]
print(a[-1],"and",b[len(b)-1])

5 and 6


In [135]:
a = list(range(0,10,2))

print(a[::-1])

TypeError: ignored

In [ ]:
A = 10

B = 20

if A > 5 & B > 15:

  print("One")

  elif A < 5 & B < 15:

    print("Two")

  else:

print("None")

In [ ]:
A = 2
B = 10
if A > 0 and B%A==0:
  print("One", end=",")

elif B > 5 and B%2 == 1:

  print("Two", end=" ")

else:

  pass

In [ ]:
A = 2

B = 3

print('Greater') if A//B==0 else print("Equal") if A//B==1 else print("Smaller")

In [ ]:
a = [[29, 'Rajesh'],[32, 'Ramesh'],[41, 'Dev']]

b = dict(a)

print(b.keys())

In [ ]:
a = {1: "Rajesh",

2: "Ramesh",

3: "Dev"}

b = list(a)

print(b[0])

In [136]:
a = tuple(range(0,5))

print(a.index(4))

TypeError: ignored

In [ ]:
a = tuple(range(0,10,2))

a[4] = 6

print(a[4])

In [ ]:
a = {1,1,2,2,3,3,4,4,5,5}

print(a)

In [ ]:
a = {1,2,3,4,5}

a.add(6)

print(a)

In [ ]:
X = 10
if X >= 0:
  if X == 0:
    print('None')
  elif X //2 == 1:
    print('Two')
  elif X**2 ==100:
    if X%2 == 0:
      print("Three")
  else:
    print("Four")
  else:
    print("Five")
else:
  print("Six")

In [ ]:
a = list(range(0,3))
b = []
for x in a:
  for j in range(len(a)-1, 0, -1):
    b.append(a[j])
print(b)

In [ ]:
i=5
while i>0:
for i in range(0,3):
  if i > 1:
    i = i - 2
    print(i)
else:
i = i - 1

In [ ]:
a = 0
b = 1
i = 1
while i < 5:
  temp = a + b
  a = b
  b = temp
  print(temp, end=" ")
i = i + 1

In [ ]:
def func(self):
  if self%2==0:
    return None
func(10)

In [ ]:
def func(*self):
  for i in self:
    if i in list(range(0,100,10)):
      print("True", end=",")
    else:
      print("False")
func(10,15)

In [ ]:
def func(**self):

  for i in self.values():

    if i%2 == 0 and i%3 == 0 in list(range(0,10)):

      print("True", end=" ")

    else:

      print("False", end=" ")

func(first= 10, second= 20)

In [ ]:
y = lambda a,b: a//2 + b//2 - 2//a//b

y(12,4)

In [ ]:
sample = [12,22,32,42,52]

x = map(lambda a: a//10, sample)

print(list(x))

In [ ]:
def func(self):

  if self % 2 == 1:

    return False

  else:

    return True

sample= [12,24,23,3,5,2]

z = filter(func, sample)

print(list(z))

In [ ]:
def func(x, y, z):

  for i in x:

    for j in y:

      print(i, end="")

  print(j, end="")

  return None

a = [1,2,3]

b = [3]

c = [5,6,7]

func(a,b,c)

In [ ]:
x = lambda x,y,z: x**y + z**x + y**x//z

x(1,1,3)

In [ ]:
class Myclass:

  def __init__(self):

    self.string = "Intellipaat"

    self.number = 2022

obj = Myclass()

print(obj.number, obj.string)

In [ ]:
class Myclass:

  def __init__(self):

    self.string = "Conor"

    self.number = 20

  def view(self):

    print(self.string[::-1], self.number//6)

obj = Myclass()

obj.view()

In [ ]:
class myClass:

  def __init__(self, name, age):

    self.name = name

    self.age = age

  def view(self):

    print([self.name, self.age])

class myclass:

  def __init__(self, name, age):

    self.name = name

    self.age = age

  def view(self):

    print([self.name, self.age])

obj1 = myClass("Devon", 29)

obj2 = myclass("Levi", 28)

print([obj1.name, obj2.age])

In [ ]:
class Name:

  def view(self):

    self.name = "Rajesh"

class Age:

  def view(self):

    self.age = 29

class Profession:

  def view(self):

    self.profession = "Teacher"

obj1 = Name()

obj2 = Age()

obj3 = Profession()

print(obj1.view(), obj2.view(), obj1.view())

In [ ]:
class Base:

  def __init__(self):

    self.name = "Ricky"

    self.age = 23

class Derived(Base):

  def __init__(self):

    super().__init__()

    self.profession = "Cricketer"

  def view(self):

    print(self.name, self.age, self.profession)

obj = Derived()

obj.view()

In [ ]:
from abc import ABC, abstractmethod

class School(ABC):

  def __init__(self):

    self.name = "Levi"

    self.age = 29

obj = School()

obj.name

In [ ]:
class Poly:

  def method(self, a, b):

    return (a**b)

  def method(self, a, b,c):

    return (a*b*c)

obj = Poly()

obj.method(3,2)

In [ ]:
class Parent:

  def __init__(self):

    self._name = "Levi"

    self.__age = 29

class Child(Parent):

  def __init__(self):

    Parent.__init__(self)

    self._name = "Devon"

  def view(self):

    return self._name

obj = Child()

obj.view()

In [ ]:
class Parent:

  def __init__(self):

    self._name = "Levi"

    self.__age = 29

class Child(Parent):

  def __init__(self):

    Parent.__init__(self)

    self._name = "Devon"

    self.__age = 28

  def view(self):

    return self.__age

obj = Child()

obj.view()

In [ ]:
class Parent:

  def __init__(self):

    self._name = "Rajesh"

    self.__age = 29

class Child(Parent):

  def __init__(self):

    Parent.__init__(self)

    self._name = "Ramesh"

  def view(self):

    return self.__age

obj = Child()

obj.view()

In [ ]:
class Poly:

  def __init__(self):

    self.name = 'Rajesh'

    self.age = 29

  def view(self):

    return None

class Child(Poly):

  def __init__(self):

    Poly.__init__(self)

  def view(self):

    self.prof = "Student"

    super().view()

    return None

obj = Poly()

obj.view()

In [ ]:
class Poly:

  def __init__(self):

    self.name = 'Devon'

    self.age = 29

  def view(self):

    print(self.name)

class Child(Poly):

  def __init__(self):

    Poly.__init__(self)

  def view(self):

    self.prof = "Levi"

    super().view()

    return None

obj = Child()

obj.view()

In [ ]:
from multipledispatch import dispatch

class Poly:

  @dispatch(int, int)

    def method(self, a, b):

      return (a**b)

      @dispatch(int, int, int)

    def method(self, a, b,c):

      return (a*b*c)

obj = Poly()

obj.method(4,2)

In [ ]:
import numpy as np
array = np.array([17, 27, 80, 39, 72, 95, 52, 85, 8, 64, 36, 15, 62, 76, 66, 67, 59, 92])

In [ ]:
import numpy as np

array = np.array([17, 27, 80, 39, 72, 95, 52, 85, 8, 64, 36, 15, 62, 76, 66, 67, 59, 92])

# Find range
range = np.max(array) - np.min(array)
print("Range:", range)

# Find IQR
q1 = np.median(array[:len(array)//2])
q3 = np.median(array[len(array)//2 + (len(array)%2):])
iqr = q3 - q1
print("IQR:", iqr)


In [137]:
import numpy as np
a = [[1, 0], [0, 1]]  
b = [[4, 1], [2, 2]]  
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [138]:
a = np.arange(3*4*5*6).reshape((3,4,5,6)) 
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3)) 
np.dot(a, b)[2,3,2,1,2,2]

499128

In [139]:
import numpy as np 
a = np.array([3, 7, 32], dtype = complex) 
print(a)

[ 3.+0.j  7.+0.j 32.+0.j]


In [140]:
import numpy as np

array1 = np.array([[1,2],[3,4]])
array2 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])

result = np.vstack((array1, array2))
print(result)

[[ 1  2]
 [ 3  4]
 [ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [144]:
import numpy as np
np.full((3,3), 'k')

array([['k', 'k', 'k'],
       ['k', 'k', 'k'],
       ['k', 'k', 'k']], dtype='<U1')

In [157]:
def bub_sort(array): 
  for i in range(0, len(array)): 
    for j in range(0, len(array) - i - 1): 
      if array[j] < array[j + 1]: 
        temp = array[j] 
        array[j] = array[j + 1] 
        array[j+1] = temp 
        return array 
my_array = np.array([20,14,25,16,45,60,12,9])
bub_sort(array)

TypeError: ignored

In [160]:
Sample = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
Sample[0:3, 1]

array([2, 5, 8])

In [161]:
import numpy
Array1 = numpy.arange(20,1,-1)
Array2 = numpy.array([1,2,3,4,5,6,7,8,9,10])
result = numpy.hstack((Array1, Array2))
print(result)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  2  3  4  5
  6  7  8  9 10]


In [165]:
from numpy.core.shape_base import hstack
Array1 = np.arange(20,2)
Array2 = np.array([1,2,3,4,5,6,7,8,9,10])
np.hstack((Array1, Array2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
array1 = np.array([[1,2],[3,4]]) 
array2 = np.array([[5,6],[7,8]])
np.hstack((array1, array2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [171]:
import numpy as np

A = np.array([[4], [12], [29]])
B = np.array([[13], [21], [4]])

cross_product = np.cross(A.ravel(), B.ravel())

print(cross_product)

[-561  361  -72]


In [173]:
A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25]) 
B = np.array([0,2,4,6,8,10,12,14,16,18,20, 22, 24])
corr_matrix = np.corrcoef(A, B)
corr_coef = corr_matrix[0, 1]

print("Correlation coefficient between A and B:", corr_coef)

Correlation coefficient between A and B: 1.0


In [175]:
import numpy as np

A = np.array([1,3,5,7,9,11,13,15,17,19,21,23,25])
B = np.array([0,2,4,6,8,10,12,14,16,18,20,22,24])

corr_matrix = np.corrcoef(A, B)

print(corr_matrix)

[[1. 1.]
 [1. 1.]]
