<a href="https://colab.research.google.com/github/Rahul-Chouhan-407/Practice_and_Assignments/blob/main/LDA_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from sklearn.datasets import load_digits
digits = load_digits()
X = digits.data
y = digits.target


In [4]:
# View the features data
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [5]:
# View the target labels
print(digits.target)

[0 1 2 ... 8 9 8]


In [6]:
num_features = digits.data.shape[1]

print("Number of features:", num_features)

Number of features: 64


In [8]:
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=42)

# Standardize the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [9]:
import numpy as np

# Assuming X_train and X_test are the standardized training and testing data
print("Training data shape:", np.shape(X_train))
print("Testing data shape:", np.shape(X_test))


Training data shape: (1437, 64)
Testing data shape: (360, 64)


In [13]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
lda = LinearDiscriminantAnalysis(n_components=9)  
X_train = lda.fit_transform(X_train, X_test)  
X_test = lda.transform(X_test)

ValueError: ignored