<a href="https://colab.research.google.com/github/Rahul-Chouhan-407/Practice_and_Assignments/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([3,5,7,2,9])

In [ ]:
print(np.sum(arr1))
print(np.max(arr1))
print(np.min(arr1))
print(np.mean(arr1))
print(np.median(arr1))
print(np.var(arr1))
print(np.std(arr1))

26
9
2
5.2
5.0
6.5600000000000005
2.5612496949731396


In [ ]:
# 2D Array
a = np.array([[1,2,3],[4,12,6],[7,8,9]])

In [ ]:
print(np.linalg.det(a))

-83.99999999999999


In [ ]:
print(np.linalg.inv(a))

[[-0.71428571 -0.07142857  0.28571429]
 [-0.07142857  0.14285714 -0.07142857]
 [ 0.61904762 -0.07142857 -0.04761905]]


In [ ]:
# Arithmetic Operations
print(arr1 + arr1)
print(arr1 - arr1)
print(arr1 * arr1)
print(arr1 ** 2)
print(arr1 / arr1)
print(arr1 // arr1)
print(arr1 % arr1)


[ 6 10 14  4 18]
[0 0 0 0 0]
[ 9 25 49  4 81]
[ 9 25 49  4 81]
[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[0 0 0 0 0]


In [ ]:
b = np.array([1,2,3])
c = np.array([4,5,6])

In [ ]:
print(b % c)

[1 2 3]


In [ ]:
print(b + 1)
print(b * 2)
print(b - 1)
print(b / 5)
print(b // 2)
print(b % 2)
print(np.concatenate((b, c), axis=0))

[2 3 4]
[2 4 6]
[0 1 2]
[0.2 0.4 0.6]
[0 1 1]
[1 0 1]
[1 2 3 4 5 6]


In [ ]:
# Concatenate vertically (along rows) using vstack
result_vertical = np.vstack((b, c))

print("Concatenated Vertically:\n", result_vertical)


Concatenated Vertically:
 [[1 2 3]
 [4 5 6]]


In [ ]:
result_horizontal = np.hstack((b, c))

print("Concatenated Horizontally:\n", result_vertical)

Concatenated Horizontally:
 [[1 2 3]
 [4 5 6]]


In [ ]:
d = np.zeros((3,3),dtype = int)
print(d)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# Create a 1D array of zeros with 5 elements
arr1d = np.zeros(5, dtype = int)

# Create a 2D array of zeros with 2 rows and 3 columns
arr2d = np.zeros((2, 3))

# Create a 3D array of zeros with dimensions 2x2x2
arr3d = np.zeros((2, 2, 2))

# Create a 2D array of zeros with a specified data type (int)
arr_int = np.zeros((3, 3), dtype=int)

# Create a 2D array of zeros with column-major order
arr_col_major = np.zeros((2, 3), order='F')


In [ ]:
print(arr1d)

[0 0 0 0 0]


In [ ]:
print(arr2d)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr_col_major

array([[0., 0., 0.],
       [0., 0., 0.]])

**Pattern Programming**

In [ ]:
# Printing a Square (5 x 5)
n = 5
for i in range(n):
  for j in range(n):
    print("*", end = " ")
  print()

* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 


In [ ]:
# Printing a increasing triangle
n = 5
for i in range(n):
  for j in range(i+1):
    print("*", end = " ")
  print()


* 
* * 
* * * 
* * * * 
* * * * * 


In [ ]:
# Increasing Triangle - Taking the input from the User
num = int(input('Enter the number of rows: '))
for i in range(num):
  for j in range(i+1):
    print("*", end = " ")
  print()

Enter the number of rows: 4
* 
* * 
* * * 
* * * * 


In [ ]:
# Printing a decreasing triangle
n = 5
for i in range(n):
  for j in range(i,n):
    print("*", end = " ")
  print()

* * * * * 
* * * * 
* * * 
* * 
* 


In [ ]:
# Right Sided Triangle
n = 5
for i in range(n):
  for j in range(i,n):
    print(" ", end = " ")
  for j in range(i+1):
    print("*", end = " ")
  print()

          * 
        * * 
      * * * 
    * * * * 
  * * * * * 


In [ ]:
# Right Sided Inverted Triangle
n = 5
for i in range(n):
  for j in range(i+1):
    print(" ", end = " ")
  for j in range(i,n):
    print("*", end = " ")
  print()

  * * * * * 
    * * * * 
      * * * 
        * * 
          * 


In [ ]:
# Hill Pattern
n = 5
for i in range(n):
  for j in range(i,n):
    print("", end = " ")
  for j in range(i+1):
    print("*", end = " ")
  print()


     * 
    * * 
   * * * 
  * * * * 
 * * * * * 


In [ ]:
# Hill Pattern (Option 2 - The real one)
n = 5
for i in range(n):
  for j in range(i,n):
    print(" ", end = " ")
  for j in range(i):
    print("*", end = " ")
  for j in range(i+1):
    print("*", end = " ")

  print()


          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 


In [ ]:
# Hill Pattern (Upside Down)
n = 5
for i in range(n):
  for j in range(i+1):
    print(" ", end = " ")
  for j in range(i+1,n):
    print("*", end = " ")
  for j in range(i,n):
    print("*", end = " ")
  print()


  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 


In [ ]:
# Diamond Pattern
n = 5
for i in range(n-1):
  for j in range(i,n):
    print(" ", end = " ")
  for j in range(i):
    print("*", end = " ")
  for j in range(i+1):
    print("*", end = " ")
  print()
for i in range(n):
  for j in range(i+1):
    print(" ", end = " ")
  for j in range(i+1,n):
    print("*", end = " ")
  for j in range(i,n):
    print("*", end = " ")
  print()

          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 


In [ ]:
# Sandglass Pattern
n = 5
for i in range(n-1):
  for j in range(i+1):
    print(" ", end = " ")
  for j in range(i+1,n):
    print("*", end = " ")
  for j in range(i,n):
    print("*", end = " ")
  print()
for i in range(n):
  for j in range(i,n):
    print(" ", end = " ")
  for j in range(i):
    print("*", end = " ")
  for j in range(i+1):
    print("*", end = " ")

  print()


  * * * * * * * * * 
    * * * * * * * 
      * * * * * 
        * * * 
          * 
        * * * 
      * * * * * 
    * * * * * * * 
  * * * * * * * * * 


In [ ]:
# Butterfly Pattern
n = 5
for i in range(n-1):
  for j in range(i+1):
    print("*", end = " ")
  for j in range(i,n):
    print(" ", end = " ")
  for j in range(i,n):
    print(" ", end = " ")
  for j in range(i+1):
    print("*", end = " ")
  print()
for i in range(n):
  for j in range(i,n):
    print("*", end = " ")
  for j in range(i+1):
    print(" ", end = " ")
  for j in range(i+1):
    print(" ", end = " ")
  for j in range(i,n):
    print("*", end = " ")
  print()

*                     * 
* *                 * * 
* * *             * * * 
* * * *         * * * * 
* * * * *     * * * * * 
* * * *         * * * * 
* * *             * * * 
* *                 * * 
*                     * 


**Pattern Programs - Alphabets**

In [ ]:
# Printing A
for i in range(7):
  for j in range(5):
    if ((j == 0 or j == 4) and i != 0) or ((i == 0 or i ==3) and (j > 0 and j < 4)):
      print("*", end = "")
    else:
      print(end = " ")
  print()

 *** 
*   *
*   *
*****
*   *
*   *
*   *


In [ ]:
# Printing B
for i in range(7):
  for j in range(5):
    if (j == 0) or (j == 4 and (i != 0 and i != 3 and i != 6)) or ((i == 0 or i == 3 or i == 6) and (j > 0 or j < 4)):
      print("*", end = " ")
    else:
      print(end = " ")
  print()

* * * * * 
*    * 
*    * 
* * * * * 
*    * 
*    * 
* * * * * 


In [ ]:
# Printing C (Type 1)
for i in range(7):
  for j in range(5):
    if (j == 0) or ((i == 0 or i == 6) and (j > 0)):
      print("*", end=" ")
    else:
      print(end=" ")
  print()

* * * * * 
*     
*     
*     
*     
*     
* * * * * 


In [ ]:
# Printing C (Type 2)
for i in range(7):
  for j in range(5):
    if ((i == 0 or i == 6)and (j > 0)) or (j == 0 and i != 0 and i != 6):
      print("*", end = " ")
    else:
      print(end = " ")
  print()

 * * * * 
*     
*     
*     
*     
*     
 * * * * 


In [ ]:
# Printing D
for i in range(7):
  for j in range(5):
    if (j == 0) or ((i==0 or i==6) and (j>0 and j<4)) or ((i!=0 and i !=6) and (j==4)):
      print("*", end="")
    else:
      print(end=" ")
  print()


**** 
*   *
*   *
*   *
*   *
*   *
**** 


In [ ]:
# Printing S
for i in range(7):
  for j in range(5):
    if (i==0 and j!=0) or ((i==3) and (j!=0 or j!=4)) or (i==6 and j!=4) or ((i==1 or i==2) and j==0) or ((i==4 or i==5) and j==4):
      print("*", end="")
    else:
      print(end=" ")
  print()

 ****
*    
*    
*****
    *
    *
**** 


In [ ]:
# Printing X
for i in range(5):
  for j in range(5):
    if (((i==0 or i==4) and (j==0 or j==4)) or (i==2 and j==2) or ((i==1 or i==3) and (j==1 or j==3))):
      print("*", end="")
    else:
      print(end=" ")
  print()

*   *
 * * 
  *  
 * * 
*   *


**Patterns using Numbers**

In [ ]:
n = int(input("Enter the number of rows needed: "))
for i in range(n):
  for j in range(i+1):
    print(j+1, end=" ")
  print()

Enter the number of rows needed: 5
1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [ ]:
n = int(input("Enter the number of rows needed: "))
for i in range(n):
  for j in range(i,-1,-1):
    print(j+1, end=" ")
  print()

Enter the number of rows needed: 5
1 
2 1 
3 2 1 
4 3 2 1 
5 4 3 2 1 


In [ ]:
n = int(input("Enter the number of rows needed: "))
for i in range(n):
  for j in range(i+1):
    print(i+1, end=" ")
  print()

Enter the number of rows needed: 5
1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [ ]:
n = int(input("Enter the number of rows needed: "))
for i in range(n,-1,-1):
  for j in range(i,-1,-1):
    print(i+1, end=" ")
  print()

Enter the number of rows needed: 5
6 6 6 6 6 6 
5 5 5 5 5 
4 4 4 4 
3 3 3 
2 2 
1 


**Table of a Number**

In [ ]:
n = int(input("Enter a number: "))
for i in range(1,11):
  print(f"{n} x {i} = {n*i}")


Enter a number: 7
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70


**Factorial of a Number**

In [ ]:
# Using FOR loop
n = int(input("Enter the number: "))
fact = 1
for i in range(1,n+1):
  fact = fact * i
print(f"Factorial of {n} is {fact}")

Enter the number: 7
Factorial of 7 is 5040


In [ ]:
# Using WHILE loop
n = int(input("Enter the number: "))
fact = 1
while (n>0):
  fact = fact * n
  n = n-1
print(f"Factorial is", fact)


Enter the number: 7
Factorial is 5040


**Fibocacci Series**

In [ ]:
# Using WHILE loop
n = int(input("Enter a number: "))
x=0
y=1
z=0
while (z<=n):
  print(z, end=" ")
  x=y
  y=z
  z=x+y

Enter a number: 7
0 1 1 2 3 5 

In [ ]:
# Using FOR loop
n = int(input("Enter the number of terms: "))
x=0
y=1
z=0
for i in range(n):
  print(z, end=" ")
  x=y
  y=z
  z=x+y


Enter the number of terms: 7
0 1 1 2 3 5 8 

**Armstrong Numbers**

In [ ]:
# Printing Armstrong Numbers
number = int(input("Enter a number till you want to find out the armstrong numbers: "))
for i in range(number):
  num=i
  result=0      # to store the results in various steps
  n=len(str(i))
  while (i>0):
    digit = i%10
    result = result + digit**n
    i = i // 10
  if num == result:
    print(num, end=" ")

Enter a number till you want to find out the armstrong numbers: 1001
0 1 2 3 4 5 6 7 8 9 153 370 371 407 

In [ ]:
# Finding out whether a number is a Armstrong Number
i = int(input("Enter a number: "))
num=i
result=0
n=len(str(i))
while(i>0):
  digit = i%10
  result = result + digit**n
  i = i//10
if (num == result):
  print(f"The number {num} is an Armstrong Number")
else:
  print(f"The number {num} is not an Armstrong Number")


Enter a number: 1001
The number 1001 is not an Armstrong Number


**Prime or not**

In [ ]:
# Checking whether a number is prime or not
n = int(input("Enter a number to check whether it is prime or not: "))
if n>1:
  for i in range(2,n):
    if n%i==0:
      print(f"{n} is not a Prime Number")
      break
  else:
    print(f"{n} is a prime number")
else:
  print(f"Zero or Negative Numbers are not allowed")

Enter a number to check whether it is prime or not: 5
5 is a prime number


**Reverse of a number**

In [ ]:
# Reverse of a number
n = int(input("Enter a number: "))
rev=0
while (n>0):
  rev = (rev*10) + n%10
  n=n//10
print(f"Reverse of the given number is {rev}")

Enter a number: 4567
Reverse of the given number is 7654


**Sum of digits of a given number**

In [ ]:
# Sum of digits of a given number
num = int(input("Enter a number to find out the sum of its digits: "))
sum=0
while (num>0):
  digit = num%10
  sum = sum + digit
  num = num // 10
print(f"Sum of digits of the given number is {sum}")

Enter a number to find out the sum of its digits: 45678
Sum of digits of the given number is 30


**Sum of square of digits of a given number**

In [ ]:
# Sum of square of digits of a given number
num = int(input("Enter a number: "))
sum=0
while (num>0):
  digit = num%10
  sum = sum + digit**2
  num = num // 10
print(f"Sum of square of digits of the given number is {sum}")

Enter a number: 5678
Sum of square of digits of the given number is 174


**Sum of cube of digits of a given number**

In [ ]:
# Sum of cube of digits of a given number
num = int(input("Enter a number: "))
sum=0
while (num>0):
  digit = num%10
  sum = sum + digit**3
  num = num // 10
print(f"Sum of cube of digits of the given number is {sum}")

Enter a number: 5678
Sum of cube of digits of the given number is 1196


**Product of digits of a given number**

In [ ]:
# Product of digits of a given number
num = int(input("Enter a number to find out the product of its digits: "))
product=1
while (num>0):
  digit = num%10
  product = product * digit
  num = num // 10
print(f"Product of digits of the given number is {product}")

Enter a number to find out the product of its digits: 5678
Product of digits of the given number is 1680


**Sum of even digits and product of odd digits of a given number**

**Print factors of a given number**

**Count total number of factors of a given number**

**Count the number of vowels and consonants**

**Program to find out the LCM**

**Program to find out the HCF**

**Printing Even and Odd Numbers**

In [ ]:
# Printing Even Numbers
for i in range(0,101,2):
  print(i, end=" ")

0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 

In [ ]:
# Printing Odd Numbers
for i in range(1,101,2):
  print(i, end=" ")

1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 

**Swap two variables without using a temporary variable**

In [ ]:
# Initial values of the variables
a = int(input("Enter the value of a: "))
b = int(input("Enter the value of b: "))

# Swapping without a temporary variable
a = a + b
b = a - b
a = a - b

# Now, 'a' contains the value that was initially in 'b', and 'b' contains the value that was initially in 'a'
print("After swapping:")
print("a =", a)
print("b =", b)

Enter the value of a: 4
Enter the value of b: 7
After swapping:
a = 7
b = 4


**Find the largest element in an array**

In [ ]:
# Define an array (list)
arr = [10, 45, 67, 23, 98, 54, 32]

# Initialize the maximum element to the first element of the array
max_element = arr[0]

# Iterate through the array to find the maximum element
for num in arr:
    if num > max_element:
        max_element = num

# Print the maximum element
print("The largest element in the array is:", max_element)

The largest element in the array is: 98


**Write a program to reverse a string**

In [ ]:
# Input string
input_string = input("Enter a string: ")

# Reverse the string using slicing
reversed_string = input_string[::-1]

# Print the reversed string
print("Reversed string:", reversed_string)

Enter a string: Rahul
Reversed string: luhaR


**Check if a string is a palindrome**

In [ ]:
input_string = input("Type in your string here: ")
# Remove spaces and convert to lowercase
clean_string = input_string.replace(" ", "").lower()

# Reverse the string
reversed_string = clean_string[::-1]

# Check if the original and reversed strings are the same
if (clean_string == reversed_string):
    print("The string is a palindrome.")
else:
    print("The string is not a palindrome.")

Type in your string here: rahul is great
The string is not a palindrome.


**Count the occurrences of a character in a string**

In [ ]:
# Input string
input_string = input("Enter a string: ")

# Input character to count
char_to_count = input("Enter a character to count: ")

# Initialize a counter for the character
count = 0

# Iterate through the string and count occurrences of the character
for char in input_string:
    if char == char_to_count:
        count += 1

# Print the count
print(f"The character '{char_to_count}' occurs {count} times in the string.")

Enter a string: rahul is rocking!
Enter a character to count: r
The character 'r' occurs 2 times in the string.


**Remove duplicates from a string**

In [ ]:
# Input string
input_string = input("Enter a string: ")

# Initialize an empty string to store unique characters
unique_string = ""

# Iterate through the input string
for char in input_string:
    # If the character is not already in the unique_string, add it
    if char not in unique_string:
        unique_string += char

# Print the string with duplicates removed
print("String with duplicates removed:", unique_string)

Enter a string: rahul is a dashing personality
String with duplicates removed: rahul isdngpeoty


**Reverse words in a sentence**

In [ ]:
# Input sentence
input_sentence = input("Enter a sentence: ")

# Split the sentence into words
words = input_sentence.split()

# Reverse the order of the words
reversed_words = words[::-1]

# Join the reversed words into a sentence
reversed_sentence = ' '.join(reversed_words)

# Print the reversed sentence
print("Reversed sentence:", reversed_sentence)

Enter a sentence: rahul is great
Reversed sentence: great is rahul


**Check if two strings are anagrams**

In [ ]:
# Input two strings
string1 = input("Enter the first string: ")
string2 = input("Enter the second string: ")

# Remove spaces and convert to lowercase for case-insensitive comparison
string1 = string1.replace(" ", "").lower()
string2 = string2.replace(" ", "").lower()

# Check if the sorted characters of both strings are the same
if sorted(string1) == sorted(string2):
  print("The strings are anagrams.")
else:
  print("The strings are not anagrams.")

Enter the first string: Rahul
Enter the second string: Chouhan
The strings are not anagrams.


**Data Structures: Implementing a Stack**

In [ ]:
# Initialize an empty stack
stack = []

# Push elements onto the stack (add to the top)
stack.append(1)
stack.append(2)
stack.append(3)

# Pop elements from the stack (remove from the top)
top_element = stack.pop()
print("Popped:", top_element)

# View the top element without removing it
if stack:
    top_element = stack[-1]
    print("Top element:", top_element)
else:
    print("Stack is empty.")

Popped: 3
Top element: 2


In [ ]:
# IMPLEMENTING STACK BY SETTING THE LIMIT
stack = []
def push():
  if len(stack) == n:
    print("Stack is full!")
  else:
    element = input("Enter the element: ")
    stack.append(element)
    print(stack)

def pop_element():
  if not stack:
    print("The stack is empty")
  else:
    e = stack.pop()
    print("Removed element: ", e)
    print(stack)
n = int(input("Set the limit of the stack: "))
while True:
  print("Select the option: 1. Push 2. Pop 3. Quit")
  choice = int(input())
  if choice == 1:
    push()
  elif choice == 2:
    pop_element()
  elif choice == 3:
    break
  else:
    print("Enter the correct operation!")

Set the limit of the stack: 5
Select the option: 1. Push 2. Pop 3. Quit
3


**Data Structures: Implementing a Queue**

In [ ]:
# Initialize an empty queue
queue = []

# Enqueue elements into the queue (add to the rear)
queue.append(1)
queue.append(2)
queue.append(3)
queue.append(4)
queue.append(5)
queue.append(6)
queue.append(7)

# Dequeue elements from the queue (remove from the front)
front_element = queue.pop(0)
print("Dequeued:", front_element)

# View the front element without removing it
if queue:
    front_element = queue[0]
    print("Front element:", front_element)
else:
    print("Queue is empty.")

Dequeued: 1
Front element: 2


In [ ]:
# IMPLEMENTING STACK BY SETTING THE LIMIT
queue = []
def push():
  if len(queue) == n:
    print("Queue is full. No more entry!")
  else:
    element = input("Enter the element: ")
    queue.append(element)
    print(queue)

def pop_element():
  if not queue:
    print("The queue is empty")
  else:
    e = queue.pop(0)
    print("Removed element: ", e)
    print(queue)
n = int(input("Set a limit for the queue: "))
while True:
  print("Select the option: 1. Push 2. Pop 3. Quit")
  choice = int(input())
  if choice == 1:
    push()
  elif choice == 2:
    pop_element()
  elif choice == 3:
    break
  else:
    print("Enter the correct operation!")

Set a limit for the queue: 3
Select the option: 1. Push 2. Pop 3. Quit
1
Enter the element: 10
['10']
Select the option: 1. Push 2. Pop 3. Quit
1
Enter the element: 20
['10', '20']
Select the option: 1. Push 2. Pop 3. Quit
1
Enter the element: 30
['10', '20', '30']
Select the option: 1. Push 2. Pop 3. Quit
1
Queue is full. No more entry!
Select the option: 1. Push 2. Pop 3. Quit
2
Removed element:  10
['20', '30']
Select the option: 1. Push 2. Pop 3. Quit
2
Removed element:  20
['30']
Select the option: 1. Push 2. Pop 3. Quit
2
Removed element:  30
[]
Select the option: 1. Push 2. Pop 3. Quit
2
The queue is empty
Select the option: 1. Push 2. Pop 3. Quit
3


In [ ]:
# QUEUE - PRACTICE

def enqueue():
  n = int(input("Enter the element to be inserted in the queue: "))
  queue.append(n)
  print(f"Element {n} inserted in the queue successfully")
  print("---------------------------")

def dequeue():
  if len(queue) == 0:
    print("The queue is empty")
    print("-------------------------")
  else:
    print(f"Element {queue[0]} deleted from the queue successfully")
    queue.pop(0)
    print("---------------------------")

def display():
  if len(queue) == 0:
    print("The queue is empty")
    print("---------------------------")
  else:
    for i in queue:
      print(i, end = " ")
    print(f"\nFront of the queue is {queue[0]}")
    print(f"Rear of the queue is {queue[-1]}")
    print("---------------------------")

queue = []

while(1):
  print("Choose the option:\n1. Enqueue\n2. Dequeue\n3. Display\n4. Exit")
  option = int(input("The option chosen is: "))
  if option == 1:
    enqueue()
  elif option == 2:
    dequeue()
  elif option == 3:
    display()
  else:
    break
    print("Please choose the correct option")


Choose the option:
1. Enqueue
2. Dequeue
3. Display
4. Exit
The option chosen is: 1
Enter the element to be inserted in the queue: 10
Element 10 inserted in the queue successfully
---------------------------
Choose the option:
1. Enqueue
2. Dequeue
3. Display
4. Exit
The option chosen is: 1
Enter the element to be inserted in the queue: 20
Element 20 inserted in the queue successfully
---------------------------
Choose the option:
1. Enqueue
2. Dequeue
3. Display
4. Exit
The option chosen is: 1
Enter the element to be inserted in the queue: 30
Element 30 inserted in the queue successfully
---------------------------
Choose the option:
1. Enqueue
2. Dequeue
3. Display
4. Exit
The option chosen is: 1
Enter the element to be inserted in the queue: 40
Element 40 inserted in the queue successfully
---------------------------
Choose the option:
1. Enqueue
2. Dequeue
3. Display
4. Exit
The option chosen is: 3
10 20 30 40 
Front of the queue is 10
Rear of the queue is 40
----------------------

**Selection Sort**

In [ ]:
# Implementing Selection Sort

arr = [9,65,4,7,34,76,2]
for i in range(len(arr)):
  min_index = i
  for j in range(i+1, len(arr)):
    if arr[j] < arr[min_index]:
      min_index = j
  arr[i], arr[min_index] = arr[min_index], arr[i]
print(arr)


[2, 4, 7, 9, 34, 65, 76]


**Merge Sort (Using Recursion)**

In [ ]:
def merge_sort(arr):
  if len(arr) > 1:
    mid = len(arr)//2
    left_arr = arr[:mid]    # Splitting the array
    right_arr = arr[mid:]
    merge_sort(left_arr)   # Recursion. Continue splitting till each array has a songle element.
    merge_sort(right_arr)
    i=0     # Initializing index of left array
    j=0     # Initializing index of right array
    k=0     # Initializing index of the main array
    while i<len(left_arr) and j<len(right_arr):
      if left_arr[i] < right_arr[j]:
        arr[k] = left_arr[i]
        i=i+1
        k=k+1
      else:
        arr[k] = right_arr[j]
        j=j+1
        k=k+1

    while i<len(left_arr):  # To check whether any element is left in the left array
      arr[k] = left_arr[i]
      i=i+1
      k=j+1

    while j<len(right_arr):  # To check whether any element is left in the right array
      arr[k] = right_arr[j]
      j=j+1
      k=k+1

num = int(input("Enter the number of elements you want to enter in an array: "))
arr = [int(input()) for x in range(num)]
merge_sort(arr)
print(arr)

Enter the number of elements you want to enter in an array7
4
6
1
9
5
4
3
[1, 3, 4, 4, 5, 6, 9]


**Quick Sort**

**Bubble Sort**

**Implementation of Binary Search Algorithm**

In [ ]:
def binary_search(arr, target):
    left, right = 0, len(arr) - 1

    while left <= right:
        mid = left + (right - left) // 2  # Calculate the middle index

        if arr[mid] == target:
            return mid  # Element found, return its index
        elif arr[mid] < target:
            left = mid + 1  # Adjust the left boundary
        else:
            right = mid - 1  # Adjust the right boundary

    return -1  # Element not found in the list

# Sorted list (you can modify this list as needed)
sorted_list = [1, 3, 5, 7, 9, 11, 13, 15]

# Target element to search for
target_element = 7

# Perform binary search
result = binary_search(sorted_list, target_element)

if result != -1:
    print(f"Element {target_element} found at index {result}")
else:
    print(f"Element {target_element} not found in the list")


Element 7 found at index 3


In [ ]:
# Swapping 2 elements in an array

def swap(a,b,arr):
  arr[a], arr[b] = arr[b], arr[a]

n = int(input("Enter the number of elements you want in an array: "))

arr = int(input("Enter the elements in the array: "))

swap(0,5,arr)
print(arr)

swap(1,4,arr)
print(arr)


[6, 2, 3, 4, 5, 1, 7]
[6, 5, 3, 4, 2, 1, 7]


In [ ]:
# Quicksort Practice
def quicksort(arr, left, right):
  if left<right:
    partition_pos = partition(arr,left,right)
    quicksort(arr,left,partition_pos - 1)
    quicksort(arr,partition_pos + 1,right)


def partition(arr, left, right):
  i = left
  j =  right - 1
  pivot = arr[right]
  while i<j:
    while i<right and arr[i] < pivot:
      i=i+1
    while j>left and arr[j] >= pivot:
      j=j-1
    if i<j:
      arr[i],arr[j]=arr[j],arr[i]
  if arr[i]>pivot:
    arr[i],arr[right]=arr[right],arr[i]
  return i

In [ ]:
a = [5,19,3,89,6,4,8,2]
quicksort(a,0,len(a)-1)
print(a)

[2, 3, 4, 5, 6, 8, 19, 89]


In [ ]:
for i in range(100):
  if i%3 == 0:
    print(i, end = " ")

0 3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 

In [ ]:
for i in range(0,100,3):
  print(i, end=" ")

0 3 6 9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81 84 87 90 93 96 99 

In [ ]:
list = []
for i in range(100):
  if i%3==0:
    list.append(i)
print(list)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [ ]:
list=[]
for i in range(0,100,3):
  list.append(i)
print(list)


[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [ ]:
ls=[i for i in range(0,100,3)]
print(ls)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [ ]:
s = "Hello World" # Using List Comprehension
l=[i for i in s]
print(l)

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']


In [ ]:
l = []                # Without using List Comprehension
s = "Hello World"
for i in s:
  l.append(i)
print(l)

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'r', 'l', 'd']


# **OOPS PRACTICE**

# **Bank ATM Application**

In [3]:
class Atm:
  def __init__(self):
    self.pin = ""
    self.balance = 0
    self.menu()

  def menu(self):
    user_input = input("""
    Hi! How are you?
    1. Press 1 to create a Pin
    2. Press 2 to change the Pin
    3. Press 3 to check your account balance
    4. Press 4 to withdraw money
    5. Press anything else to exit
    """)

    if user_input == '1':
      self.create_pin()
      self.menu()

    elif user_input == '2':
      self.change_pin()


    elif user_input == '3':
      self.check_balance()

    elif user_input == '4':
      self.withdraw_money()

    else:
      exit()

  def create_pin(self):
    user_pin = input("Enter your desired 4 digit PIN: ")
    self.pin = user_pin
    user_balance = int(input("Enter your balance: "))
    self.balance = user_balance
    print("Pin created successfully!")
    self.menu()

  def change_pin(self):
    old_pin = input("Enter your existing PIN: ")
    if old_pin == self.pin:
      new_pin = input("Enter your new PIN: ")
      self.pin = new_pin
      print("PIN changed successfully!")
      self.menu()
    else:
      print("Wrong Old Pin! Cannot let you change it.")
      self.menu()

  def check_balance(self):
    user_pin = input("Enter your PIN: ")
    if user_pin == self.pin:
      print("Your balance is", self.balance)
    else:
      print("Wrong Pin entered!")
    self.menu()

  def withdraw_money(self):
    user_pin = input("Enter your Pin: ")
    if user_pin == self.pin:
      amount = int(input("Enter the amount to withdraw: "))
      if self.balance > amount:
        self.balance = self.balance - amount
        print("Amount withdrawn is", amount)
        print("Your new balance is", self.balance)
      else:
        print("Insufficient Balance")
    self.menu()


In [4]:
obj=Atm()


    Hi! How are you?
    1. Press 1 to create a Pin
    2. Press 2 to change the Pin
    3. Press 3 to check your account balance
    4. Press 4 to withdraw money
    5. Press anything else to exit
    1
Enter your desired 4 digit PIN: 1234
Enter your balance: 10000
Pin created successfully!

    Hi! How are you?
    1. Press 1 to create a Pin
    2. Press 2 to change the Pin
    3. Press 3 to check your account balance
    4. Press 4 to withdraw money
    5. Press anything else to exit
    3
Enter your PIN: 1234
Your balance is 10000

    Hi! How are you?
    1. Press 1 to create a Pin
    2. Press 2 to change the Pin
    3. Press 3 to check your account balance
    4. Press 4 to withdraw money
    5. Press anything else to exit
    4
Enter your Pin: 1234
Enter the amount to withdraw: 3000
Amount withdrawn is 3000
Your new balance is 7000

    Hi! How are you?
    1. Press 1 to create a Pin
    2. Press 2 to change the Pin
    3. Press 3 to check your account balance
    4. Press 4 t

# **Creating your own Data Type: Fraction**

In [19]:
class Fraction:
  def __init__(self,x,y):
    self.numerator = x
    self.denominator = y

  def __str__(self):
    return "{}/{}".format(self.numerator,self.denominator)

  def __add__(self,other):
    new_numerator = self.numerator*other.denominator + self.denominator*other.numerator
    new_denominator = self.denominator*other.denominator

    return "{}/{}".format(new_numerator,new_denominator)

  def __sub__(self,other):
    new_numerator = self.numerator*other.denominator - self.denominator*other.numerator
    new_denominator = self.denominator*other.denominator

    return "{}/{}".format(new_numerator,new_denominator)

  def __mul__(self,other):
    new_numerator = self.numerator*other.numerator
    new_denominator = self.denominator*other.denominator

    return "{}/{}".format(new_numerator,new_denominator)

  def __truediv__(self,other):
    new_numerator = self.numerator*other.denominator
    new_denominator = self.denominator*other.numerator

    return "{}/{}".format(new_numerator,new_denominator)

  def convert_to_decimal(self):
    return self.numerator/self.denominator

In [21]:
fr1 = Fraction(3,4)
fr2 = Fraction(5,6)
print(fr1 + fr2)
print(fr1-fr2)
print(fr2-fr1)
print(fr1*fr2)
print(fr1/fr2)
fr1.convert_to_decimal()
fr2.convert_to_decimal()

38/24
-2/24
2/24
15/24
18/20


0.8333333333333334

# **OOP Classes to handle the below scenarios:**

1.   A user can write and view 2D coordinates
2.   Finding out distance between 2 coordinates
1.   Finding out the distance of coordinates from origin
2.   Check if the point lies on a given line
1.   Finding out the distance between a given 2D point and a given line







In [59]:
class Point:

  def __init__(self,x,y):
    self.x_cord = x
    self.y_cord = y

  def __str__(self):
    return "<{},{}>".format(self.x_cord,self.y_cord)

  def euclidean_distance(self,other):
    return ((self.x_cord - other.x_cord)**2 + (self.y_cord - other.y_cord)**2)**0.5

  def dist_from_origin(self):
    return (self.x_cord**2 + self.y_cord**2)**0.5

class Line:

  def __init__(self,A,B,C):
    self.A = A
    self.B = B
    self.C = C

  def __str__(self):
    return "{}x + {}y + {} = 0".format(self.A,self.B,self.C)

  def point_on_line(line,point):
    if line.A*point.x_cord + line.B*point.y_cord + line.C == 0:
      return "Point lies on the line"
    else:
      return "Point does not lie on the line"

  def shortest_distance(line,point):
    return abs(line.A*point.x_cord + line.B*point.y_cord + line.C)/(line.A**2 + line.B**2)**0.5


In [61]:
l1 = Line(1,1,-2)
print(l1)
p1 = Point(3,2)
print(p1)
l1.shortest_distance(p1)

1x + 1y + -2 = 0
<3,2>


2.1213203435596424

In [39]:
p1 = Point(3,2)
print(p1)
p2 = Point(4,3)
print(p2)
p1.euclidean_distance(p2)
p1.dist_from_origin()

<3,2>
<4,3>


3.605551275463989

# **Class Relationships:**

1.   Aggregation
2.   Inheritance



## **Aggregation**

In [65]:
class Customer:
  def __init__(self, name,gender,address):
    self.name = name
    self.gender = gender
    self.address = address

  def print_address(self):
    print(self.address.houseno, self.address.colony, self.address.landmark, self.address.city, self.address.pincode, self.address.state)

class Address:
  def __init__(self,houseno,colony,landmark,city,pincode,state):
    self.houseno = houseno
    self.colony = colony
    self.landmark = landmark
    self.city = city
    self.pincode = pincode
    self.state = state

In [66]:
add1 = Address(175, 'Sacchidanand Nagar', 'Kesharbagh Road', 'Indore', 452009, 'Madhya Pradesh')
print(add1)

In [67]:
cust1 = Customer('Rahul', 'Male', add1)
print(cust1)

In [69]:
cust1.print_address()
print(cust1.name)
print(cust1.gender)

175 Sacchidanand Nagar Kesharbagh Road Indore 452009 Madhya Pradesh
Rahul
Male
