<a href="https://colab.research.google.com/github/Rahul-Chouhan-407/Practice_and_Assignments/blob/main/Python_for_DS_Evaluation_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/sp500_companies.csv")

In [3]:
df.head()

Exchange Symbol              Shortname               Longname  \
0      NMS   AAPL             Apple Inc.             Apple Inc.   
1      NMS   MSFT  Microsoft Corporation  Microsoft Corporation   
2      NMS   GOOG          Alphabet Inc.          Alphabet Inc.   
3      NMS  GOOGL          Alphabet Inc.          Alphabet Inc.   
4      NMS   AMZN       Amazon.com, Inc.       Amazon.com, Inc.   

                   Sector                        Industry  Currentprice  \
0              Technology            Consumer Electronics        148.03   
1              Technology         Software—Infrastructure        255.14   
2  Communication Services  Internet Content & Information        101.45   
3  Communication Services  Internet Content & Information        100.99   
4       Consumer Cyclical                 Internet Retail         96.54   

       Marketcap        Ebitda  Revenuegrowth           City State  \
0  2354875990016  1.305410e+11          0.081      Cupertino    CA   
1  1915585953792  9.798300e+10          0.124        Redmond    WA   
2  1311241142272  9.373300e+10          0.061  Mountain View    CA   
3  1308729278464  9.373300e+10          0.061  Mountain View    CA   
4   984872189952  5.154900e+10          0.147        Seattle    WA   

         Country  Fulltimeemployees  \
0  United States           164000.0   
1  United States           221000.0   
2  United States           186779.0   
3  United States           186779.0   
4  United States          1544000.0   

                                 Longbusinesssummary    Weight  
0  Apple Inc. designs, manufactures, and markets ...  0.064857  
1  Microsoft Corporation develops, licenses, and ...  0.052759  
2  Alphabet Inc. provides various products and pl...  0.036114  
3  Alphabet Inc. provides various products and pl...  0.036045  
4  Amazon.com, Inc. engages in the retail sale of...  0.027125

In [5]:
df.shape

(495, 16)

In [6]:
df.isnull().sum()

Exchange                0
Symbol                  0
Shortname               0
Longname                0
Sector                  0
Industry                0
Currentprice            0
Marketcap               0
Ebitda                 42
Revenuegrowth          12
City                    0
State                  20
Country                 0
Fulltimeemployees       5
Longbusinesssummary     0
Weight                  0
dtype: int64

In [18]:
df['Sector'].nunique()

11

In [19]:
# Find the company with the highest market cap
max_marketcap = df["Marketcap"].max()
company_with_max_marketcap = df.loc[df["Marketcap"] == max_marketcap, "Shortname"].iloc[0]

print(f"The company with the highest market cap is {company_with_max_marketcap} with a market cap of {max_marketcap}.")


The company with the highest market cap is Apple Inc. with a market cap of 2354875990016.


Which company has the highest currentprice?

a. Amazon.com Inc
b. NVR, Inc
c. Alphabet Inc
d. Apple Inc

In [20]:
# Find the company with the highest currentprice cap
max_currentprice = df["Currentprice"].max()
company_with_max_currentprice = df.loc[df["Currentprice"] == max_currentprice, "Shortname"].iloc[0]

print(f"The company with the highest Currentprice cap is {company_with_max_currentprice} with a Currentprice of {max_currentprice}.")

The company with the highest Currentprice cap is NVR, Inc. with a Currentprice of 4639.01.


Which company has fulltimeemployees more than 2000000?

a. Alphabet Inc
b. Apple Inc
c. Amazon.com Inc
d. Walmart Inc

In [23]:
# filter companies with fulltimeemployees > 2000000
filtered_df = df[df['Fulltimeemployees'] > 2000000]

# get the company with highest marketcap
company_with_flt = filtered_df.loc[filtered_df['Fulltimeemployees'].idxmax(), 'Shortname']

print("Company with fulltimeemployees more than 2000000:", company_with_flt)


Company with fulltimeemployees more than 2000000: Walmart Inc.


In [21]:
df['Fulltimeemployees'] > 2000000

0      False
1      False
2      False
3      False
4      False
       ...  
490    False
491    False
492    False
493    False
494    False
Name: Fulltimeemployees, Length: 495, dtype: bool

In [7]:
df.duplicated().sum()

0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495 entries, 0 to 494
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Exchange             495 non-null    object 
 1   Symbol               495 non-null    object 
 2   Shortname            495 non-null    object 
 3   Longname             495 non-null    object 
 4   Sector               495 non-null    object 
 5   Industry             495 non-null    object 
 6   Currentprice         495 non-null    float64
 7   Marketcap            495 non-null    int64  
 8   Ebitda               453 non-null    float64
 9   Revenuegrowth        483 non-null    float64
 10  City                 495 non-null    object 
 11  State                475 non-null    object 
 12  Country              495 non-null    object 
 13  Fulltimeemployees    490 non-null    float64
 14  Longbusinesssummary  495 non-null    object 
 15  Weight               495 non-null    flo

In [10]:
df.describe()

Currentprice     Marketcap        Ebitda  Revenuegrowth  \
count    495.000000  4.950000e+02  4.530000e+02     483.000000   
mean     171.673717  7.335043e+10  6.159371e+09       0.816487   
std      290.379414  1.784558e+11  1.227018e+10      12.465281   
min        5.470000  3.335212e+09 -2.681000e+09      -0.444000   
25%       59.920000  1.662387e+10  1.418000e+09       0.018500   
50%      107.580000  3.106965e+10  2.627000e+09       0.088000   
75%      194.015000  6.414280e+10  5.706000e+09       0.193500   
max     4639.010000  2.354876e+12  1.305410e+11     270.791000   

       Fulltimeemployees      Weight  
count       4.900000e+02  495.000000  
mean        5.545089e+04    0.002020  
std         1.447732e+05    0.004915  
min         1.050000e+02    0.000092  
25%         9.438500e+03    0.000458  
50%         1.940000e+04    0.000856  
75%         5.388700e+04    0.001767  
max         2.300000e+06    0.064857

In [11]:
# What is the output of the following code?
x = [4,2,1,6,3,6,8,0,5,2,1,7,0,2]
np.var(x, ddof=1)

7.016483516483515

In [12]:
A = np.array([[3,2],[4,1],[2,5]])
B = np.array([[6,11],[4,12],[2,15]])
np.cross(A,B)

array([21, 44, 20])

In [13]:
A = np.array([4,5,6])
B = np.array([1,2,3])
np.hstack((B,A))

array([1, 2, 3, 4, 5, 6])

In [14]:
# What will be the output of the following code?
A = np.array([[4],[5],[6]])
B = np.array([[1],[2],[3]])
np.column_stack((A,B))

array([[4, 1],
       [5, 2],
       [6, 3]])

In [ ]:
A = np.array([1,2,3,4,5])

In [25]:
# Group the companies by state and count the number of companies in each state
state_counts = df.groupby('State')['Shortname'].count()

# Sort the states based on the count of companies and take the first row to get the state with the most number of sp500 companies
state_with_most_companies = state_counts.sort_values(ascending=False).index[0]

print("State with the most number of sp500 companies:", state_with_most_companies)


State with the most number of sp500 companies: CA


In [27]:
# Filter for revenue growth greater than 0.1 and sort by current price
filtered_df = df[df['Revenuegrowth'] > 0.1].sort_values('Currentprice')

# Print the company with the lowest current price
print(filtered_df.iloc[0]['Shortname'])

Carnival Corporation


In [30]:
california_companies = df[df['State'] == 'CA']
sector_count = california_companies['Sector'].value_counts()
most_common_sector = sector_count.index[0]
print("The sector with the most number of companies in California is:", most_common_sector)



The sector with the most number of companies in California is: Technology


In [34]:
# Compute the correlation matrix
corr_matrix = df.corr()


<ipython-input-34-5f6d38d23b14>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = df.corr()


In [35]:
# Calculate the correlation matrix between all columns
corr_matrix = df.corr()

# Print the correlation values between each pair of columns
print(corr_matrix)

                   Currentprice  Marketcap    Ebitda  Revenuegrowth  \
Currentprice           1.000000   0.031924 -0.018301      -0.027836   
Marketcap              0.031924   1.000000  0.889062      -0.020162   
Ebitda                -0.018301   0.889062  1.000000      -0.034846   
Revenuegrowth         -0.027836  -0.020162 -0.034846       1.000000   
Fulltimeemployees      0.003568   0.352247  0.332915      -0.007083   
Weight                 0.031924   1.000000  0.889062      -0.020162   

                   Fulltimeemployees    Weight  
Currentprice                0.003568  0.031924  
Marketcap                   0.352247  1.000000  
Ebitda                      0.332915  0.889062  
Revenuegrowth              -0.007083 -0.020162  
Fulltimeemployees           1.000000  0.352247  
Weight                      0.352247  1.000000  


<ipython-input-35-1bbac2a0718d>:2: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  corr_matrix = df.corr()
